<main>
  <section style="height: 74%;">
    <div class="container">
      <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 36rem;">
          <div class="card-body">

            <div class="d-flex justify-content-center mb-3">
              <img src="../images/logo.svg" width="300" height="80"/>
            </div>

            <div class="row mb-3">
              <div class="col">
                <h2 class="text-center">Cadastro realizado com sucesso</h2>
              </div>
            </div>

            <div class="row text-center">
              <div class="col">
                <a href="/" class="btn btn-danger btn-block">Clique aqui para fazer login!</a>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>
</main>


    
  