<main>
  <section style="height: 80%;">
    <div class="container bg-light">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="../images/logo.svg" alt="" width="72" height="57"> <!--inclusão do logo-->
        <h2>Cadastro</h2>
        <p class="lead">Preencha as informações solicitadas abaixo para concluir o seu cadastro.</p>
      </div>

      <div class="col-md-7 col-lg-8">
        <form class="needs-validation" action="/registrar" method="post">
            <div class="col-6 mb-3">
              <label class="form-label">Matrícula UniRitter</label>
              <div class="input-group has-validation">
                <input type="text" class="form-control" id="username" value="<?= $this->view->usuario['matricula_uniritter'] ?>" name="matricula_uniritter" required>
                <div class="invalid-feedback">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="row g-3 mb-3">
              <div class="col-sm-12">
                <label for="firstName" class="form-label">Nome</label>
                <input type="text" class="form-control" id="firstName" value="<?= $this->view->usuario['nome'] ?>" name="nome" required>             
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
            </div>

            <div class="col-12 mb-3">
              <label for="email" class="form-label">E-mail</label>
              <input type="email" class="form-control" id="email" placeholder="you@example.com" value="<?= $this->view->usuario['email'] ?>" name="email" required>
              <div class="invalid-feedback">
                Por favor informe um e-mail válido.
              </div>
            </div>

            <div class="col-12 mb-3">
              <label for="address" class="form-label">Senha</label>
              <input type="password" class="form-control" id="address" placeholder="12345" value="<?= $this->view->usuario['senha'] ?>" name="senha" required>
              <div class="invalid-feedback">
                Por favor informe uma senha válida.
              </div>
            </div>

            <hr class="my-3">

            <div class="form-check mb-3">
              <input type="checkbox" class="form-check-input" id="save-info">
              <label class="form-check-label" for="save-info">Salvar dados para próximo login</label>
            </div>

            <button class="w-100 btn btn-lg btn-danger" type="submit">Inscrever-se</button>

            <?php if($this->view->erroCadastro) { ?>

              <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>

            <?php } ?>

        </form>
      </div>
    </div>
  </section>
</main>


