<main>
  <section class="py-5 text-center container" style="margin-top: 160px;">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Encontre materiais aqui</h1>
        <p class="lead text-dark">Todos trabalhos, materiais de aula, TCCs, pappers e muito mais para você acessar quando e onde quiser, fácil rápido e prático! Pesquise pelo nome do usuário que postou os arquivos!</p>
    
        <form action="/pesquisar" method="GET">
          <div class="col-12 input-group">
              <input type="text" name="nome_usuario" class="form-control my-2"> 
              <button class="btn btn-danger my-2"><i class="fas fa-search"></i></button>
          </div>
        </form>
       </div>
    </div>
  </section>
</main>


