<html>
	<head>
		<meta charset="utf-8" />
		<title>Repositório UniRitter</title>

		<!-- Bootstrap 5 -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

		<!-- Bootstrap 5 JS Bundle -->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

		<!-- Font Awesome -->
		<script src="https://kit.fontawesome.com/e3025b49ae.js" crossorigin="anonymous"></script>

		<!-- jQuery -->
		<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

		<!-- CSS Proprietário -->
		<link href="..\css\index.css" rel="stylesheet">

		<!-- Normalize CSS -->
		<link href="../css/normalize.css" rel="stylesheet">

	</head>

	<body>
	
	    <?= $this->content() ?>
        
		<footer class="bg-dark mt-5">
			<div class="container">
				<div class="row">		
					<div class="col-md-4">
						<ul>
							<li class="li-tel-footer text-white">
								<h6>Atendimento Telefônico e Online</span></h6>
								<span>De Segunda à sexta das 10h às 21h Sábados das 9h às 12h</span>
							</li>
						</ul> 
					</div>

					<div class="col-md-4">
						<ul>
							<li class="li-tel-footer text-white">
								<h6><p class="ml-3 mb-3">Copyright &copy; 2021 - All Rights Reserved - Repositório UniRitter</p></h6>
							</li>
						</ul> 
					</div>

					<div class="col-md-4 ml-auto">
						<a href="https://pt-br.facebook.com/UniRitter" class="btn btn-outline-light ml-2">
						<i class="fab fa-facebook"></i>
						</a>
						<a href="https://twitter.com/UniRitter" class="btn btn-outline-light ml-2">
						<i class="fab fa-twitter"></i>
						</a>
						<a href="https://www.instagram.com/uniritter/" class="btn btn-outline-light ml-2">
						<i class="fab fa-instagram"></i>
						</a>
						<a href="https://www.youtube.com/user/conexaouniritter" class="btn btn-outline-light ml-2">
						<i class="fab fa-youtube"></i>
						</a>
						<a href="https://api.whatsapp.com/send?1=pt_BR&phone=555130925600&text=%20Ol%C3%A1,%20UniRitter!" class="btn btn-outline-light ml-2">
						<i class="fab fa-whatsapp"></i>
						</a>
						<a href="tel:555140034951" class="btn btn-outline-light ml-2">
						<i class="fas fa-phone-square-alt"></i>
						</a>						
					</div>
				</div>
			</div>
    	</footer>

    </body>

</html>